format code
using shfmt
using shellcheck

diff --git a/git-autofixup b/git-autofixup
--- a/git-autofixup
+++ b/git-autofixup
@@ -1,23 +1,23 @@
 #!/bin/sh
 set -e
 
-make_relative () {
-    while read f; do
-        git relative-path "$f"
-    done
+make_relative() {
+        while read f; do
+                git relative-path "$f"
+        done
 }
 
 FILES="$(git diff --no-prefix --cached -U0 | awk '/^--- / { print $2 }' | grep -vF /dev/null | make_relative)"
 if [ -z "$FILES" ]; then
-  echo "No staged files found that have previously been committed." >&2
-  exit 2
+        echo "No staged files found that have previously been committed." >&2
+        exit 2
 fi
 
 SHA="$(git last-commit-to-file $FILES)"
 
 if [ -n "$SHA" ]; then
-  git commit --fixup "$SHA" --no-verify
+        git commit --fixup "$SHA" --no-verify
 else
-  echo "Could not determine which commit last touched the staged files." >&2
-  exit 3
+        echo "Could not determine which commit last touched the staged files." >&2
+        exit 3
 fi
diff --git a/git-cherry-pick-to b/git-cherry-pick-to
--- a/git-cherry-pick-to
+++ b/git-cherry-pick-to
@@ -1,21 +1,21 @@
 #!/bin/sh
 set -e
 
-usage () {
-    echo "usage: git cherry-pick-to <branch> ..." >&2
+usage() {
+        echo "usage: git cherry-pick-to <branch> ..." >&2
 }
 
 if [ $# -eq 0 ]; then
-    usage
-    exit 2
+        usage
+        exit 2
 fi
 
 branch="$1"
 shift 1
 
 if git is-dirty -a; then
-    echo 'Cannot use this command safely when you have local files marked "skipped".' >&2
-    exit 2
+        echo 'Cannot use this command safely when you have local files marked "skipped".' >&2
+        exit 2
 fi
 
 # TODO: FIXME: There is a lot that can go wrong here.  Basically, that's not
diff --git a/git-cleanup b/git-cleanup
--- a/git-cleanup
+++ b/git-cleanup
@@ -1,44 +1,50 @@
 #!/bin/sh
 set -e
 
-usage () {
-    echo "usage: git cleanup [-lr] [-nsvh]" >&2
-    echo >&2
-    echo "Deletes all branches that have already been merged into the main branch." >&2
-    echo "Removes those branches both locally or in the origin remote (or both)." >&2
-    echo "Will be most conservative with deletions." >&2
-    echo >&2
-    echo "Minimally requires either (or both) of these flags to be set:" >&2
-    echo "-l    Remove local branches" >&2
-    echo "-r    Remove remote branches (in \`origin\`)" >&2
-    echo >&2
-    echo "Options:" >&2
-    echo "-n    Dry-run" >&2
-    echo "-s    Also consider squash merges (implies -l)" >&2
-    echo "-v    Be verbose (show what's skipped)" >&2
-    echo "-h    Show this help" >&2
+usage() {
+        echo "usage: git cleanup [-lr] [-nsvh]" >&2
+        echo >&2
+        echo "Deletes all branches that have already been merged into the main branch." >&2
+        echo "Removes those branches both locally or in the origin remote (or both)." >&2
+        echo "Will be most conservative with deletions." >&2
+        echo >&2
+        echo "Minimally requires either (or both) of these flags to be set:" >&2
+        echo "-l    Remove local branches" >&2
+        echo "-r    Remove remote branches (in \`origin\`)" >&2
+        echo >&2
+        echo "Options:" >&2
+        echo "-n    Dry-run" >&2
+        echo "-s    Also consider squash merges (implies -l)" >&2
+        echo "-v    Be verbose (show what's skipped)" >&2
+        echo "-h    Show this help" >&2
 }
 
 dryrun=0
-locals=0
-remotes=0
+locals=1
+remotes=1
 squashed=0
 verbose=0
 while getopts nlrsvh flag; do
-    case "$flag" in
-        n) dryrun=1;;
-        l) locals=1;;
-        r) remotes=1;;
-        s) squashed=1; locals=1;;
-        v) verbose=1;;
-        h) usage; exit 2;;
-    esac
+        case "$flag" in
+        n) dryrun=1 ;;
+        l) locals=1 ;;
+        r) remotes=1 ;;
+        s)
+                squashed=1
+                locals=1
+                ;;
+        v) verbose=1 ;;
+        h)
+                usage
+                exit 2
+                ;;
+        esac
 done
 shift $(($OPTIND - 1))
 
 if [ $remotes -eq 0 ] && [ $locals -eq 0 ]; then
-    usage
-    exit 1
+        usage
+        exit 1
 fi
 
 #
@@ -49,12 +55,12 @@ fi
 #   - master (local) + origin/master
 #
 
-safegit () {
-    if [ "$dryrun" -eq 1 ]; then
-        echo git "$@"
-    else
-        git "$@"
-    fi
+safegit() {
+        if [ "$dryrun" -eq 1 ]; then
+                echo git "$@"
+        else
+                git "$@"
+        fi
 }
 
 #
@@ -66,35 +72,35 @@ safegit () {
 # - Idem for each remote branch
 #
 
-find_common_base () {
-    if [ $# -eq 1 ]; then
-        git sha "$1"
-    else
-        git merge-base "$1" "$2"
-    fi
+find_common_base() {
+        if [ $# -eq 1 ]; then
+                git sha "$1"
+        else
+                git merge-base "$1" "$2"
+        fi
 }
 
-find_branch_base () {
-    branch="$1"
-    base_point=""
+find_branch_base() {
+        branch="$1"
+        base_point=""
 
-    if git local-branch-exists "$branch"; then
-        base_point=$(find_common_base "$branch" $base_point)
-    fi
+        if git local-branch-exists "$branch"; then
+                base_point=$(find_common_base "$branch" $base_point)
+        fi
 
-    if git remote-branch-exists origin "$branch"; then
-        base_point=$(find_common_base "origin/$branch" $base_point)
-    fi
+        if git remote-branch-exists origin "$branch"; then
+                base_point=$(find_common_base "origin/$branch" $base_point)
+        fi
 
-    if [ -n "$base_point" ]; then
-        echo "$base_point"
-    fi
+        if [ -n "$base_point" ]; then
+                echo "$base_point"
+        fi
 }
 
 main="$(git main-branch)"
 
-find_bases () {
-    find_branch_base "$main"
+find_bases() {
+        find_branch_base "$main"
 }
 
 bases=$(find_bases)
@@ -107,103 +113,103 @@ bases=$(find_bases)
 # - If it has, then delete the branch
 #
 
-clean_squashed () {
-    branch="$1"
+clean_squashed() {
+        branch="$1"
 
-    # Find the merge base for this branch
-    merge_base=$(git merge-base "$main" "$branch")
+        # Find the merge base for this branch
+        merge_base=$(git merge-base "$main" "$branch")
 
-    # Get the tree object of the branch
-    branch_tree="$(git rev-parse "$branch^{tree}")"
+        # Get the tree object of the branch
+        branch_tree="$(git rev-parse "$branch^{tree}")"
 
-    # Create a squashed commit object of the branch tree with parent
-    # of $base with a commit message of "_"
-    dangling_squashed_commit="$(git commit-tree "$branch_tree" -p "$merge_base" -m _)"
+        # Create a squashed commit object of the branch tree with parent
+        # of $base with a commit message of "_"
+        dangling_squashed_commit="$(git commit-tree "$branch_tree" -p "$merge_base" -m _)"
 
-    # Show a summary of what has yet to be applied
-    cherry_commit="$(git cherry "$main" "$dangling_squashed_commit")"
+        # Show a summary of what has yet to be applied
+        cherry_commit="$(git cherry "$main" "$dangling_squashed_commit")"
 
-    if [ "$cherry_commit" = "- $dangling_squashed_commit" ]; then
-        # If "- <commit-sha>", (ex. - "- 851cb44727") this means the
-        # commit is in main and can be dropped if you rebased
-        # against main
-        safegit branch -D "$branch"
-    elif [ $verbose -eq 1 ]; then
-        # If "+ <commit-sha>", (ex. - "+ 851cb44727") this means the
-        # commit still needs to be kept so that it will be applied to
-        # main
-        echo "Skipped $branch (no similar squash found)"
-    fi
+        if [ "$cherry_commit" = "- $dangling_squashed_commit" ]; then
+                # If "- <commit-sha>", (ex. - "- 851cb44727") this means the
+                # commit is in main and can be dropped if you rebased
+                # against main
+                safegit branch -D "$branch"
+        elif [ $verbose -eq 1 ]; then
+                # If "+ <commit-sha>", (ex. - "+ 851cb44727") this means the
+                # commit still needs to be kept so that it will be applied to
+                # main
+                echo "Skipped $branch (no similar squash found)"
+        fi
 }
 
 if [ $locals -eq 1 ]; then
-    for branch in $(git local-branches \
-                    | grep -vxF "$main"); do
-        for base in $bases; do
-            if git contains "$base" "$branch"; then
-                if ! git contains "$branch" "$base"; then
-                    # Actually delete
-                    if ! safegit branch -D "$branch"; then
-                        echo "Errors deleting local branch $branch" >&2
-                    fi
-                    break
-                fi
-            else
-                # This is the case where the branches are in fact legit
-                # local WIP branches or they are squashed merges, and we
-                # need to check if they have been squashed-merged into
-                # main. NOTE - this assumes main is up-to-date locally
-                if [ "$squashed" -eq 1 ]; then
-                    clean_squashed "$branch"
-                fi
-            fi
+        for branch in $(git local-branches |
+                grep -vxF "$main"); do
+                for base in $bases; do
+                        if git contains "$base" "$branch"; then
+                                if ! git contains "$branch" "$base"; then
+                                        # Actually delete
+                                        if ! safegit branch -D "$branch"; then
+                                                echo "Errors deleting local branch $branch" >&2
+                                        fi
+                                        break
+                                fi
+                        else
+                                # This is the case where the branches are in fact legit
+                                # local WIP branches or they are squashed merges, and we
+                                # need to check if they have been squashed-merged into
+                                # main. NOTE - this assumes main is up-to-date locally
+                                if [ "$squashed" -eq 1 ]; then
+                                        clean_squashed "$branch"
+                                fi
+                        fi
+                done
         done
-    done
 fi
 
 # Pruning first will remove any remote tracking branches that don't exist in
 # the remote anymore anyway.
 if [ $remotes -eq 1 ]; then
-    remote=origin
-    safegit remote prune "$remote" >/dev/null 2>/dev/null
+        remote=origin
+        safegit remote prune "$remote" >/dev/null 2>/dev/null
 
-    if [ $remotes -eq 1 ]; then
-        branches_to_remove=""
-        for branch in $(git remote-branches "$remote" | grep -vEe "/($main)\$"); do
-            for base in $bases; do
-                if git contains "$base" "$branch"; then
-                    if ! git contains "$branch" "$base"; then
-                        branchname=$(echo "$branch" | cut -d/ -f2-)
-                        branches_to_remove="$branches_to_remove $branchname"
-                        break
-                    fi
+        if [ $remotes -eq 1 ]; then
+                branches_to_remove=""
+                for branch in $(git remote-branches "$remote" | grep -vEe "/($main)\$"); do
+                        for base in $bases; do
+                                if git contains "$base" "$branch"; then
+                                        if ! git contains "$branch" "$base"; then
+                                                branchname=$(echo "$branch" | cut -d/ -f2-)
+                                                branches_to_remove="$branches_to_remove $branchname"
+                                                break
+                                        fi
+                                fi
+                        done
+                done
+
+                if [ -n "$branches_to_remove" ]; then
+                        if ! safegit push "$remote" --delete $branches_to_remove; then
+                                echo "Errors deleting branches $branches_to_remove from remote '$remote'" >&2
+                        fi
                 fi
-            done
-        done
-
-        if [ -n "$branches_to_remove" ]; then
-            if ! safegit push "$remote" --delete $branches_to_remove; then
-                echo "Errors deleting branches $branches_to_remove from remote '$remote'" >&2
-            fi
         fi
-    fi
 fi
 
 # Delete any remaining local remote-tracking branches of remotes that are gone.
 if [ $locals -eq 1 ]; then
-    branches_to_remove=""
-    for branch in $(git remote-branches); do
-        for base in $bases; do
-            if git contains "$base" "$branch"; then
-                if ! git contains "$branch" "$base"; then
-                    branches_to_remove="$branches_to_remove $branch"
-                    break
-                fi
-            fi
+        branches_to_remove=""
+        for branch in $(git remote-branches); do
+                for base in $bases; do
+                        if git contains "$base" "$branch"; then
+                                if ! git contains "$branch" "$base"; then
+                                        branches_to_remove="$branches_to_remove $branch"
+                                        break
+                                fi
+                        fi
+                done
         done
-    done
 
-    if [ -n "$branches_to_remove" ]; then
-        safegit branch -dr $branches_to_remove
-    fi
+        if [ -n "$branches_to_remove" ]; then
+                safegit branch -dr $branches_to_remove
+        fi
 fi
diff --git a/git-relative-path b/git-relative-path
--- a/git-relative-path
+++ b/git-relative-path
@@ -5,18 +5,18 @@ root="$(git root)"
 realpath_bin="$(which grealpath realpath 2>/dev/null | head -n1 || true)"
 
 if [ ! -x "$realpath_bin" ]; then
-    echo "'realpath' or 'grealpath' utility not found. Please install GNU coreutils." >&2
-    exit 1
+        echo "'realpath' or 'grealpath' utility not found. Please install GNU coreutils." >&2
+        exit 1
 fi
 
 if ! "$realpath_bin" --version 2>/dev/null | grep -q GNU; then
-    echo "I expected the 'realpath' utility to be the GNU version." >&2
-    echo "$realpath_bin: not the GNU version" >&2
-    echo "Please install GNU coreutils and try again." >&2
-    exit 2
+        echo "I expected the 'realpath' utility to be the GNU version." >&2
+        echo "$realpath_bin: not the GNU version" >&2
+        echo "Please install GNU coreutils and try again." >&2
+        exit 2
 fi
 
 while [ $# -gt 0 ]; do
-    "$realpath_bin" --relative-to=. "$root/$1"
-    shift
+        "$realpath_bin" --relative-to=. "$root/$1"
+        shift
 done
diff --git a/git-update-all b/git-update-all
--- a/git-update-all
+++ b/git-update-all
@@ -1,26 +1,29 @@
 #!/bin/sh
 set -e
 
-usage () {
-    echo "usage: git update-all [-h] [remote]" >&2
-    echo >&2
-    echo "Updates (pulls) upstream changes on all local branches." >&2
-    echo "remote defaults to origin." >&2
-    echo >&2
-    echo "Options:" >&2
-    echo "-h    Show this help" >&2
+usage() {
+        echo "usage: git update-all [-h] [remote]" >&2
+        echo >&2
+        echo "Updates (pulls) upstream changes on all local branches." >&2
+        echo "remote defaults to origin." >&2
+        echo >&2
+        echo "Options:" >&2
+        echo "-h    Show this help" >&2
 }
 
 while getopts h flag; do
-    case "$flag" in
-        h) usage; exit 2;;
-    esac
+        case "$flag" in
+        h)
+                usage
+                exit 2
+                ;;
+        esac
 done
 shift $(($OPTIND - 1))
 
 if git is-dirty; then
-    echo "Cannot do this while your working copy has local changes.  Stash or commit them first." >&2
-    exit 2
+        echo "Cannot do this while your working copy has local changes.  Stash or commit them first." >&2
+        exit 2
 fi
 
 remote=${1:-origin}
@@ -29,24 +32,24 @@ curr=$(git current-branch)
 git fetch --quiet
 
 for branch in $(git local-branches); do
-    if git remote-branch-exists "$remote" "$branch"; then
-        if [ "$branch" != "$(git current-branch)" ]; then
-            git checkout --quiet "$branch" >/dev/null 2>/dev/null
-        fi
+        if git remote-branch-exists "$remote" "$branch"; then
+                if [ "$branch" != "$(git current-branch)" ]; then
+                        git checkout --quiet "$branch" >/dev/null 2>/dev/null
+                fi
 
-        orig_sha=$(git sha -s "$branch")
-        new_sha=$(git sha -s "$remote"/"$branch")
-        if [ "$orig_sha" != "$new_sha" ] && git contains "$remote"/"$branch" "$branch"; then
-            if git merge --quiet --ff-only "$remote/$branch"; then
-                echo "updated '$branch' to latest '$remote/$branch' ($orig_sha...$new_sha)"
-            else
-                echo "warning: could not fast-forward '$branch' to '$remote/$branch': branches have diverged." >&2
-            fi
+                orig_sha=$(git sha -s "$branch")
+                new_sha=$(git sha -s "$remote"/"$branch")
+                if [ "$orig_sha" != "$new_sha" ] && git contains "$remote"/"$branch" "$branch"; then
+                        if git merge --quiet --ff-only "$remote/$branch"; then
+                                echo "updated '$branch' to latest '$remote/$branch' ($orig_sha...$new_sha)"
+                        else
+                                echo "warning: could not fast-forward '$branch' to '$remote/$branch': branches have diverged." >&2
+                        fi
+                else
+                        echo "skipping: branch '$branch' is already up-to-date or newer than '$remote/$branch'" >&2
+                fi
         else
-            echo "skipping: branch '$branch' is already up-to-date or newer than '$remote/$branch'" >&2
+                echo "skipping: branch '$branch' is not on '$remote'" >&2
         fi
-    else
-        echo "skipping: branch '$branch' is not on '$remote'" >&2
-    fi
 done
 git checkout --quiet "$curr"
